node('TestMachine-ut') {
    stage('Updating Slave Container'){
        sh 'apt-get update && apt-get install git'
    }
    stage ('Fetching Docker-Compose File') {
        sh 'cd /tmp/ && wget https://github.com/mms-cv/ci-cd-project/blob/master/docker-compose.yml'
    }
    stage ('Docker Compose UP') {
        sh 'cd /tmp/ && docker-compose up -d"'
    }
    stage ('Unitesting') {
        sh 'echo "Building"'
    }
}